version: '3.9'

services:
  server:
    build: .
    container_name: 'server'
    ports:
     - '5000:5000'
  db:
    image: 'postgres'
    container_name: 'db'
    # ports:
    #   - 4321:5432
    environment:
      POSTGRES_PASSWORD: "password"
      POSTGRES_USER: 'username'
    volumes:
      - data:/var/lib/postgresql/data
  mongodb:
    image: mongo
    container_name: 'mongodb'
    ports:
     - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: 'admin'
      MONGO_INITDB_ROOT_PASSWORD: 'password'
    volumes:
      - mongodb_data:/var/lib/mongodb/data

volumes:
  data:
  mongodb_data:
